version: '3.9'

services:
  infolaft_app:
    container_name: prueba-infolaft
    image: infolaft:v1
    build: .
    ports:
      - 9000:9000
    depends_on:
      - infolaft_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/dbinfolaft
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - pruebaInfolaft

  infolaft_db:
    container_name: db_infolaft
    image: postgres
    ports:
      - 5432:5432
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbinfolaft
    networks:
      - pruebaInfolaft

networks:
  pruebaInfolaft:
    driver: bridge
